### ISSUE TITLE
KeyError: 'data' when placing limit order

### ISSUE THREAD

**Issue by zwocram** [tastyware/tastytrade#136]
Hi, using the example from https://tastyworks-api.readthedocs.io/en/latest/orders.html I get the following error:

  File ".........../venv/lib/python3.11/site-packages/tastytrade/account.py", line 1032, in place_order
    data = response.json()['data']
           ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

This is my code. I use a sandbox.
```
       account = Account.get_account(session, account_number)

        symbol = Equity.get_equity(session, 'USO')
        leg = symbol.build_leg(Decimal('5'), OrderAction.BUY_TO_OPEN)  # buy to open 5 shares

        order = NewOrder(
            time_in_force=OrderTimeInForce.DAY,
            order_type=OrderType.LIMIT,
            legs=[leg],  # you can have multiple legs in an order
            price=Decimal('10'),  # limit price, $10/share for a total value of $50
            price_effect=PriceEffect.DEBIT
        )
 
        response = account.place_order(session, order, dry_run=True)

 ```
Am I doing something wrong?
thanks!
regards

**Comment by Graeme22** [comment]
Hello! This is working for me with a certification session. Could you provide more data please?

**Comment by zwocram** [comment]
Sure! What kind of data for example?
Thanks!

**Comment by zwocram** [comment]
Hi, you mean the traceback maybe? I copied most of the code from readthedocs so  my code is practically the same. THis is the code:
```
from tastytrade import CertificationSession
session = CertificationSession(username, password)

account = Account.get_account(session, account_number)
symbol = Equity.get_equity(session, 'USO')
leg = symbol.build_leg(Decimal('5'), OrderAction.BUY_TO_OPEN)  # buy to open 5 shares

try:
    order = NewOrder(
        time_in_force=OrderTimeInForce.DAY,
        order_type=OrderType.LIMIT,
        legs=[leg],  # you can have multiple legs in an order
        price=Decimal('10'),  # limit price, $10/share for a total value of $50
        price_effect=PriceEffect.DEBIT
    )
    response = account.place_order(session, order, dry_run=True)  # a test order
except Exception as e:
    logging.error("An error occurred: ", str(e))
finally:
    session.destroy()
```

This is the traceback:
```
2024-04-05 14:37:55,205 - ERROR - internal_server_error: Internal server error. Unique customer support identifier: 437c79f72b0d25b5c7c57dc03d4319d3
--- Logging error ---
Traceback (most recent call last):
  File "/home/marco/Documents/01 Projects/tastyapp/tests.py", line 34, in <module>
    response = account.place_order(session, order, dry_run=True)  # a test order
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/Documents/01 Projects/tastyapp/venv/lib/python3.11/site-packages/tastytrade/account.py", line 1032, in place_order
    data = response.json()['data']
           ~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/logging/__init__.py", line 1110, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 953, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 687, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/logging/__init__.py", line 377, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/marco/Documents/01 Projects/tastyapp/tests.py", line 36, in <module>
    logging.error("An error occurred: ", str(e))
Message: 'An error occurred: '
Arguments: ("'data'",)
```

**Comment by Graeme22** [comment]
What happens if you use a ProductionSession? (As long as you do dry_run=True the trade won't actually be placed.) I suspect it's a problem with your cert account.

**Comment by zwocram** [comment]
Thanks for the suggestion, I tried that and it looks like no errors for the PRD session. Strange, isn't it? I tried in postman for the certificationsession and no errors there; order was sent.
Well, I'll close this question for now. Thanks for your time, I'll dive more into this.
Kind regards
