### ISSUE TITLE
pydantic ValidationError in PlacedOrder due to missing fields in FillInfo

### ISSUE THREAD

**Issue by DavidDotCheck** [tastyware/tastytrade#89]
**Describe the bug**
When accessing my account's orders using either account.get_live_orders or account.get_order_history, the following error happens:
```
Traceback (most recent call last):
  File "C:\Users\Me\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Me\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Users\Me\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\Users\Me\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main       
    run()
  File "c:\Users\Me\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 284, in run_file   
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\Me\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "c:\Users\Me\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "c:\Users\Me\.vscode\extensions\ms-python.python-2023.14.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "c:\Path\To\Project\tastytrade.py", line 328, in <module>
    print("Orders:", account.get_live_orders(session))
  File "c:\Path\To\Project\.venv\lib\site-packages\tastytrade\account.py", line 827, in get_live_orders
    return [PlacedOrder(**entry) for entry in data]
  File "c:\Path\To\Project\.venv\lib\site-packages\tastytrade\account.py", line 827, in <listcomp>
    return [PlacedOrder(**entry) for entry in data]
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for PlacedOrder
legs -> 0 -> fills -> 0 -> ext-group-fill-id
  field required (type=value_error.missing)
legs -> 0 -> fills -> 0 -> ext-exec-id
  field required (type=value_error.missing)
```
This is caused by the FillInfo class marking neither ext_group_fill_id nor ext_exec_id as optional.
Since my most recent order seems to be lacking this information, Pydantic raises a validation error.

I haven't checked whether or not ext_group_fill_id and ext_exec_id are used anywhere in the library, but if not the solution should be as easy as making ext_group_fill_id and ext_exec_id optional. 

This is the FillInfo class I'm using currently:
```python
class FillInfo(TastytradeJsonDataclass):
    """
    Dataclass that contains information about an order fill.
    """
    ext_group_fill_id: Optional[str]
    ext_exec_id: Optional[str]
    fill_id: str
    quantity: Decimal
    fill_price: Decimal
    filled_at: datetime
    destination_venue: str
```

**How to reproduce**
The order that seems to be the issue was created like this:
```python
investment_amount = 5.00 + 0.05 # 5€ minimum for fractional investments + 0.05€ rounding error

ask_price = actions.get_quote("SPY").askPrice

fractional_shares = round(investment_amount / ask_price)

symbol = Equity.get_equity(session, "SPY")

leg = symbol.build_leg(
    Decimal(fractional_shares),
    OrderAction.BUY_TO_OPEN
)

tiny_order = NewOrder(
    time_in_force=OrderTimeInForce.DAY,
    order_type=OrderType.MARKET, 
    legs=[leg],
    price_effect=PriceEffect.DEBIT
)

response = actions.place_order(tiny_order, dry_run=False)

account.get_live_orders(session) # <-- this raises the error
```
You can safely ignore actions. It only passes the session to the function and does some local caching for quotes.
I'm using python 3.9.13, Venv, Windows 11 and tastytrade 6.1.

**Comment by Graeme22** [comment]
Thanks for opening the issue!

**Comment by DavidDotCheck** [comment]
You're welcome! Thanks for the fix :)
